codecov:
  branch: main

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment: false
ignore:
- '**/__init__.py'
- '**/print_versions.py'
